### ISSUE TITLE
search highlight widget not positioned properly

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#458]
The widget for dismissing search highlights can be pretty intrusive on DMC right now because of positioning. For example, I went to DMC and searched for "geospatial", then chose the Tutorials facet and eventually ended up here:

http://developer.marklogic.com/learn/maps-for-appbuilder-apps?hq=geospatial

Instead of being off in the upper right corner, the widget is nearish the middle. Also, this page doesn't have pinned header, so, as you scroll, the widget just floats around a couple inches below the top of the content. It is very intrusive. See below.

![highlight-widget](https://cloud.githubusercontent.com/assets/1951367/6469771/00973ad8-c194-11e4-8a19-736a0a5de708.jpg)

Not sure who this should get assigned to, so plopping in Dave's lap for starters

**Comment by dsokolsky** [comment]
I think this is fixed now with the latest set of changes.  Kim, does it look fixed to you?

**Comment by kcoleman-marklogic** [comment]
Not sure how I'm supposed to tell until it's deployed to DMC since it wasn't on docs/pubs that I observed this. Is it live? If so, then it isn't fixed.

**Comment by kcoleman-marklogic** [comment]
Also, I don't see a checkin comment associated with this issue that suggests it was fixed. Reassigning back to you for disposition, Danny.

**Comment by dsokolsky** [comment]
Yes, the fix is live on dmc (deployed as part of 7.0-5).  Kim, do you not see it there?

**Comment by kcoleman-marklogic** [comment]
Not it is not fixed on DMC. I think perhaps you're confusing this with the other problem with the highlight widget (inability to dismiss it) that _is_ fixed. 

I originally reported this issue there, and Mike said it was not the same and asked me to file another issue, which is this one. This is a problem with the positioning of the widget, as reflected by the screenie above.

**Comment by dsokolsky** [comment]
OK, I see it now.  It is a little better, I think.  is no longer blocks when you don't scroll (although it should be at the right).  But it does stay in the middle of the screen when you scroll.  That is only a problem on the developer side of the site.

On docs, it does get pinned, and it is on the right, although it does block the upper controls on the upper right part of the page (pdf and/or print and/or js/xquery func link).

Pass this to Dave.  We probably need to define something in the page layout for this.

**Comment by kcoleman-marklogic** [comment]
The behavior is unchanged.

It is positioned exactly where it was before - smack in the middle of the page horizontally, and at what amounts to the bottom of the article title section, vertically. Pinning itself to the bottom of title area is what causes it to appear to float as you scroll. It's the wrong position along both dimensions.

**Comment by dsokolsky** [comment]
OK, I was just looking at the screen shot above where it is blocking the text.  It will still do that if it is scrolled down, but not when the page is initially loaded (at least not for me).

**Comment by dmcassel** [comment]
Fixed. Thanks @kcoleman-marklogic
